### ISSUE TITLE
[Android] Can't use bullet physics

### ISSUE THREAD

**Issue by KonstantTom** [LOFI/gdx-scala-demo#3]
Hello! Bullet physics works successfully on desktop build, but it crashes on android in Bullet.init() .
For test I add 2 lines to demo:

```
import com.badlogic.gdx.physics.bullet.Bullet
...
override def create() {
    Bullet init ()
    ...
}
```

And in android build I recieve this stacktrace:

```
10-14 15:05:43.211: E/AndroidRuntime(8109): FATAL EXCEPTION: GLThread 681
10-14 15:05:43.211: E/AndroidRuntime(8109): Process: gdx.scala.demo.android, PID: 8109
10-14 15:05:43.211: E/AndroidRuntime(8109): java.lang.NoSuchMethodError: no static method with name='SwigDirector_btIDebugDraw_drawLine__SWIG_0' signature='(Lcom/badlogic/gdx/physics/bullet/linearmath/btIDebugDraw;Lcom/badlogic/gdx/math/Vector3;Lcom/badlogic/gdx/math/Vector3;Lcom/badlogic/gdx/math/Vector3;)V' in class Lcom/badlogic/gdx/physics/bullet/linearmath/LinearMathJNI;
10-14 15:05:43.211: E/AndroidRuntime(8109):     at com.badlogic.gdx.physics.bullet.linearmath.LinearMathJNI.swig_module_init(Native Method)
10-14 15:05:43.211: E/AndroidRuntime(8109):     at com.badlogic.gdx.physics.bullet.linearmath.LinearMathJNI.<clinit>(Unknown Source)
10-14 15:05:43.211: E/AndroidRuntime(8109):     at com.badlogic.gdx.physics.bullet.linearmath.a.a(Unknown Source)
10-14 15:05:43.211: E/AndroidRuntime(8109):     at com.badlogic.gdx.physics.bullet.a.a(Unknown Source)
10-14 15:05:43.211: E/AndroidRuntime(8109):     at gdx.scala.demo.a.a(Unknown Source)
10-14 15:05:43.211: E/AndroidRuntime(8109):     at com.badlogic.gdx.backends.android.h.onSurfaceChanged(Unknown Source)
10-14 15:05:43.211: E/AndroidRuntime(8109):     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1512)
10-14 15:05:43.211: E/AndroidRuntime(8109):     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

Android app build from gradle command line using android:build. I think, proguard rename some classes, but I don't know, how fix it. Help, please.

**Comment by photex** [comment]
Hi @KonstantTom I'll take a look and see if there isn't something obvious.

**Comment by KonstantTom** [comment]
Hi @photex !
This code in proguard-project.txt doesn't solve problem: :(

```
-keep public class com.badlogic.gdx.physics.bullet.** {
  *;
}
```

**Comment by KonstantTom** [comment]
No news about this issue?
This proguard code doesn't help: :(

```
-keepclassmembers class com.badlogic.gdx.physics.bullet.** {
    *;
}

-keep class com.badlogic.gdx.physics.bullet.**
```

Full decoded stacktrace:

```
10-16 20:08:27.783: E/AndroidRuntime(4714): FATAL EXCEPTION: GLThread 315
10-16 20:08:27.783: E/AndroidRuntime(4714): Process: gdx.scala.demo.android, PID: 4714
10-16 20:08:27.783: E/AndroidRuntime(4714): java.lang.NoSuchMethodError: no static method with name='SwigDirector_btIDebugDraw_drawLine__SWIG_0' signature='(Lcom/badlogic/gdx/physics/bullet/linearmath/btIDebugDraw;Lcom/badlogic/gdx/math/Vector3;Lcom/badlogic/gdx/math/Vector3;Lcom/badlogic/gdx/math/Vector3;)V' in class Lcom/badlogic/gdx/physics/bullet/linearmath/LinearMathJNI;
10-16 20:08:27.783: E/AndroidRuntime(4714):     at com.badlogic.gdx.physics.bullet.linearmath.LinearMathJNI.swig_module_init(Native Method)
10-16 20:08:27.783: E/AndroidRuntime(4714):     at com.badlogic.gdx.physics.bullet.linearmath.LinearMathJNI.<clinit>(LinearMathJNI.java:625)
10-16 20:08:27.783: E/AndroidRuntime(4714):     at com.badlogic.gdx.physics.bullet.linearmath.LinearMath.btGetVersion(LinearMath.java:63)
10-16 20:08:27.783: E/AndroidRuntime(4714):     at com.badlogic.gdx.physics.bullet.Bullet.init(Bullet.java:64)
10-16 20:08:27.783: E/AndroidRuntime(4714):     at com.badlogic.gdx.physics.bullet.Bullet.init(Bullet.java:52)
10-16 20:08:27.783: E/AndroidRuntime(4714):     at com.badlogic.gdx.physics.bullet.Bullet.init(Bullet.java:44)
10-16 20:08:27.783: E/AndroidRuntime(4714):     at com.ekit.birdsmail.a.a(Main.scala:42)
10-16 20:08:27.783: E/AndroidRuntime(4714):     at com.badlogic.gdx.backends.android.h.onSurfaceChanged(AndroidGraphics.java:241)
10-16 20:08:27.783: E/AndroidRuntime(4714):     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1512)
10-16 20:08:27.783: E/AndroidRuntime(4714):     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

( Line 42 at Main.scala is Bullet.init() )

**Comment by photex** [comment]
My apologies but my daughter was just born and I haven't between able to look at this. Gimme a few more days :)

**Comment by KonstantTom** [comment]
Ok, sorry. :)

**Comment by photex** [comment]
Hello! I'm here, I'm alive! I'll try and get this resolved asap. Sorry for taking so many ... days/months ... but life is life.

**Comment by photex** [comment]
I've verified the issue. The build works fine, but once it's loaded on the device I see this stacktrace on logcat.

**Comment by photex** [comment]
Ok @KonstantTom I've just pushed an update to the repo that fixes this. You weren't far off the mark there, but your net wasn't cast wide enough.

I updated the README to reflect the state of things but at least the default won't bail when using Bullet.

**Comment by KonstantTom** [comment]
Thank you for work! :+1: 
At this moment I don't work with libgdx, but I think this fix will be very useful for others. :)
